---
driver:
  name: local
provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[test_cookbook::default]
    attributes:
